### ISSUE TITLE
Implement observe_position_velocity method

### ISSUE THREAD

**Issue by avsaase** [nordmoen/eskf-rs#8]
Hi, thanks for making this library. 

There is a method `observe_position_velocity2d` but not an equivalent method that takes a 3d velocity. GPS units generally provide velocity in north, east and down direction and it would be convenient to include everything in one `observe_` call. Looking at the implementation it seems trivial to add this method. Are you open to a PR to add this or is there a specific reason it's omitted?

**Comment by nordmoen** [comment]
There is no reason not to add that method, as you said it should be quite straight forward. It has been some time since I worked on this and used it, but I think at the time the GPS receiver I had (and others I had worked on) did not give "GPS" velocity in 3D. It should be noted that "GPS" velocity is different from any post processing velocity that your GPS unit might output. "GPS" velocity is based on the red-shift of the GPS signal which can be used to calculate how fast your unit is moving relative to the motion of the GPS satellite. This velocity is very accurate and is therefor very useful to include to correct velocity drift. I know that some GPS units integrates this information with position information and can thus give 3D velocity, but this is the pre-processed. I might be completely of base and beside that, the method could easily be included.
